use anyhow::{anyhow, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::info;
use merix_skills::{Skill, SkillMetadata, SkillRegistry};
use merix_memory::MemoryLayer;
use merix_mcp::ToolRegistry;
use merix_schemas::SessionId;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowPattern {
    pub pattern_id: String,
    pub description: String,
    pub frequency: usize,
    pub suggested_skill_name: String,
}

pub struct SelfExtensionCore {
    skill_registry: Arc<SkillRegistry>,
    memory: Arc<MemoryLayer>,
    patterns: RwLock<Vec<WorkflowPattern>>,
}

impl SelfExtensionCore {
    pub fn new(skill_registry: Arc<SkillRegistry>, memory: Arc<MemoryLayer>) -> Self {
        Self {
            skill_registry,
            memory,
            patterns: RwLock::new(vec![]),
        }
    }

    pub async fn analyze_history(&self, session_id: SessionId) -> Result<Vec<WorkflowPattern>> {
        let context = self.memory.reconstruct_context(session_id).await?;
        info!("Analyzing history for self-extension (context length: {})", context.len());

        let patterns = vec![
            WorkflowPattern {
                pattern_id: "task-decomposition".to_string(),
                description: "Repeated task breakdown into steps".to_string(),
                frequency: 3,
                suggested_skill_name: "auto_decomposer".to_string(),
            },
        ];

        let mut stored = self.patterns.write().await;
        *stored = patterns.clone();

        Ok(patterns)
    }

    pub async fn generate_skill_from_pattern(&self, pattern: &WorkflowPattern) -> Result<()> {
        info!("Generating new skill from pattern: {}", pattern.suggested_skill_name);

        let generated_skill = GeneratedSkill {
            metadata: SkillMetadata {
                name: pattern.suggested_skill_name.clone(),
                version: "0.1.0".to_string(),
                description: format!("Auto-generated from pattern: {}", pattern.description),
                author: "Self-Extension Core".to_string(),
                capabilities: vec!["memory_read".to_string(), "tool_call".to_string()],
            },
        };

        self.skill_registry.register_skill(generated_skill).await?;
        info!("New skill registered via self-extension: {}", pattern.suggested_skill_name);
        Ok(())
    }

    pub async fn run_self_extension(&self, session_id: SessionId) -> Result<()> {
        let patterns = self.analyze_history(session_id).await?;
        for pattern in &patterns {
            self.generate_skill_from_pattern(pattern).await?;
        }
        Ok(())
    }
}

#[derive(Clone)]
struct GeneratedSkill {
    metadata: SkillMetadata,
}

#[async_trait]
impl Skill for GeneratedSkill {
    fn metadata(&self) -> SkillMetadata {
        self.metadata.clone()
    }

    async fn execute(
        &self,
        _input: Value,
        memory: &MemoryLayer,
        _tools: &ToolRegistry,
        session_id: Option<SessionId>,
    ) -> Result<Value> {
        let session_id = session_id.ok_or_else(|| anyhow!("session_id required"))?;
        let context = memory.reconstruct_context(session_id).await?;
        Ok(serde_json::json!({
            "status": "executed_generated_skill",
            "context_preview": context.chars().take(200).collect::<String>(),
            "message": "Skill was auto-generated by Self-Extension Core"
        }))
    }
}